# Generated by Django 3.2.16 on 2023-10-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0004_auto_20231016_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthday',
            name='image',
            field=models.ImageField(blank=True, upload_to='birthday_images', verbose_name='Фото'),
        ),
    ]
